name: academicollab
services:
  backend:
    build:
      context: /home/heritier/academicollab/backend
      dockerfile: Dockerfile
    command:
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8000
    container_name: academicollab_backend
    depends_on:
      db:
        condition: service_started
        required: true
    environment:
      DB_HOST: db
      DB_NAME: academicollab
      DB_PASSWORD: development_secure_password_123
      DB_PORT: "5432"
      DB_USER: academic_admin
      DEBUG: "1"
    networks:
      collab_network: null
    ports:
      - mode: ingress
        target: 8000
        published: "8000"
        protocol: tcp
    volumes:
      - type: bind
        source: /home/heritier/academicollab/backend
        target: /app
        bind: {}

  db:
    container_name: academicollab_db
    environment:
      POSTGRES_DB: academicollab
      POSTGRES_PASSWORD: development_secure_password_123
      POSTGRES_USER: academic_admin
    image: postgres:16-alpine
    networks:
      collab_network: null
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
    volumes:
      - type: volume
        source: pg_data
        target: /var/lib/postgresql/data
        volume: {}

  frontend:
    build:
      context: /home/heritier/academicollab/frontend
      dockerfile: Dockerfile
    container_name: academicollab_frontend
    depends_on:
      backend:
        condition: service_started
        required: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks:
      collab_network: null
    ports:
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: /home/heritier/academicollab/frontend
        target: /app
        bind: {}

networks:
  collab_network:
    name: academicollab_collab_network
    driver: bridge

volumes:
  pg_data:
    name: academicollab_pg_data
    driver: local
