# backend/authentication/roles.py

# Normalized Global System String Tokens
ROLE_ADMIN = 'ADMIN'
ROLE_SUPERVISOR = 'SUPERVISOR'
ROLE_FACULTY = 'FACULTY'
ROLE_STUDENT = 'STUDENT'

ALL_PLATFORM_ROLES = [
    ROLE_ADMIN,
    ROLE_SUPERVISOR,
    ROLE_FACULTY,
    ROLE_STUDENT
]