# Generated by Django 5.1.15 on 2026-06-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanbancolumn',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kanbancolumn',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='kanbancolumn',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
