# Generated by Django 5.1.15 on 2026-06-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_remove_kanbancolumn_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanbancolumn',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='kanbancolumn',
            name='order',
        ),
        migrations.AddField(
            model_name='kanbancolumn',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Visual ordering parameter from left to right.'),
        ),
    ]
