# Generated by Django 5.1.15 on 2026-06-02 20:50

import kanban_board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=kanban_board.models.default_start_date),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=kanban_board.models.default_due_date),
        ),
    ]
