# Generated by Django 5.1.15 on 2026-06-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='task',
            name='column_order',
            field=models.IntegerField(default=0, help_text='Maintains layout sort sequence for drag-and-drop updates. Unique constraints decoupled to prevent indexing locks.'),
        ),
    ]
