# Generated by Django 5.1.15 on 2026-06-17 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0002_alter_task_unique_together_alter_task_column_order'),
        ('kanban', '0002_remove_kanbancolumn_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='kanban.kanbancolumn'),
        ),
        migrations.AlterField(
            model_name='task',
            name='column_order',
            field=models.IntegerField(default=0, help_text='Sort sequence within the board column.'),
        ),
    ]
